package app.dulliesanddungeons.ui

/** Compact SRD 5.2.1 standard catalog used by the local add flow. */
data class StandardWeaponTemplate(
    val id: String,
    val name: String,
    val damage: String,
    val damageType: String,
    val ability: String,
    val properties: String,
    val range: String = "",
    val mastery: String = "",
)

val standardWeaponCatalog = listOf(
    StandardWeaponTemplate("club", "Club", "1d4", "Bludgeoning", "STR", "Light", mastery = "Slow"),
    StandardWeaponTemplate("dagger", "Dagger", "1d4", "Piercing", "DEX", "Finesse, light, thrown", "20/60 ft", "Nick"),
    StandardWeaponTemplate("greatclub", "Greatclub", "1d8", "Bludgeoning", "STR", "Two-handed", mastery = "Push"),
    StandardWeaponTemplate("handaxe", "Handaxe", "1d6", "Slashing", "STR", "Light, thrown", "20/60 ft", "Vex"),
    StandardWeaponTemplate("javelin", "Javelin", "1d6", "Piercing", "STR", "Thrown", "30/120 ft", "Slow"),
    StandardWeaponTemplate("light-hammer", "Light Hammer", "1d4", "Bludgeoning", "STR", "Light, thrown", "20/60 ft", "Nick"),
    StandardWeaponTemplate("mace", "Mace", "1d6", "Bludgeoning", "STR", "", mastery = "Sap"),
    StandardWeaponTemplate("quarterstaff", "Quarterstaff", "1d6", "Bludgeoning", "STR", "Versatile (1d8)", mastery = "Topple"),
    StandardWeaponTemplate("sickle", "Sickle", "1d4", "Slashing", "STR", "Light", mastery = "Nick"),
    StandardWeaponTemplate("spear", "Spear", "1d6", "Piercing", "STR", "Thrown, versatile (1d8)", "20/60 ft", "Sap"),
    StandardWeaponTemplate("light-crossbow", "Light Crossbow", "1d8", "Piercing", "DEX", "Ammunition, loading, two-handed", "80/320 ft", "Slow"),
    StandardWeaponTemplate("dart", "Dart", "1d4", "Piercing", "DEX", "Finesse, thrown", "20/60 ft", "Vex"),
    StandardWeaponTemplate("shortbow", "Shortbow", "1d6", "Piercing", "DEX", "Ammunition, two-handed", "80/320 ft", "Vex"),
    StandardWeaponTemplate("sling", "Sling", "1d4", "Bludgeoning", "DEX", "Ammunition", "30/120 ft", "Slow"),
    StandardWeaponTemplate("battleaxe", "Battleaxe", "1d8", "Slashing", "STR", "Versatile (1d10)", mastery = "Topple"),
    StandardWeaponTemplate("flail", "Flail", "1d8", "Bludgeoning", "STR", "", mastery = "Sap"),
    StandardWeaponTemplate("glaive", "Glaive", "1d10", "Slashing", "STR", "Heavy, reach, two-handed", mastery = "Graze"),
    StandardWeaponTemplate("greataxe", "Greataxe", "1d12", "Slashing", "STR", "Heavy, two-handed", mastery = "Cleave"),
    StandardWeaponTemplate("greatsword", "Greatsword", "2d6", "Slashing", "STR", "Heavy, two-handed", mastery = "Graze"),
    StandardWeaponTemplate("halberd", "Halberd", "1d10", "Slashing", "STR", "Heavy, reach, two-handed", mastery = "Cleave"),
    StandardWeaponTemplate("lance", "Lance", "1d10", "Piercing", "STR", "Heavy, reach, two-handed unless mounted", mastery = "Topple"),
    StandardWeaponTemplate("longsword", "Longsword", "1d8", "Slashing", "STR", "Versatile (1d10)", mastery = "Sap"),
    StandardWeaponTemplate("maul", "Maul", "2d6", "Bludgeoning", "STR", "Heavy, two-handed", mastery = "Topple"),
    StandardWeaponTemplate("morningstar", "Morningstar", "1d8", "Piercing", "STR", "", mastery = "Sap"),
    StandardWeaponTemplate("pike", "Pike", "1d10", "Piercing", "STR", "Heavy, reach, two-handed", mastery = "Push"),
    StandardWeaponTemplate("rapier", "Rapier", "1d8", "Piercing", "DEX", "Finesse", mastery = "Vex"),
    StandardWeaponTemplate("scimitar", "Scimitar", "1d6", "Slashing", "DEX", "Finesse, light", mastery = "Nick"),
    StandardWeaponTemplate("shortsword", "Shortsword", "1d6", "Piercing", "DEX", "Finesse, light", mastery = "Vex"),
    StandardWeaponTemplate("trident", "Trident", "1d8", "Piercing", "STR", "Thrown, versatile (1d10)", "20/60 ft", "Topple"),
    StandardWeaponTemplate("war-pick", "War Pick", "1d8", "Piercing", "STR", "Versatile (1d10)", mastery = "Sap"),
    StandardWeaponTemplate("warhammer", "Warhammer", "1d8", "Bludgeoning", "STR", "Versatile (1d10)", mastery = "Push"),
    StandardWeaponTemplate("whip", "Whip", "1d4", "Slashing", "DEX", "Finesse, reach", mastery = "Slow"),
    StandardWeaponTemplate("blowgun", "Blowgun", "1", "Piercing", "DEX", "Ammunition, loading", "25/100 ft", "Vex"),
    StandardWeaponTemplate("hand-crossbow", "Hand Crossbow", "1d6", "Piercing", "DEX", "Ammunition, light, loading", "30/120 ft", "Vex"),
    StandardWeaponTemplate("heavy-crossbow", "Heavy Crossbow", "1d10", "Piercing", "DEX", "Ammunition, heavy, loading, two-handed", "100/400 ft", "Push"),
    StandardWeaponTemplate("longbow", "Longbow", "1d8", "Piercing", "DEX", "Ammunition, heavy, two-handed", "150/600 ft", "Slow"),
    StandardWeaponTemplate("musket", "Musket", "1d12", "Piercing", "DEX", "Ammunition, loading, two-handed", "40/120 ft", "Slow"),
    StandardWeaponTemplate("pistol", "Pistol", "1d10", "Piercing", "DEX", "Ammunition, loading", "30/90 ft", "Vex"),
)

val standardEquipmentCatalog = listOf(
    EquipmentUi("backpack", "Backpack", details = "Carries gear"),
    EquipmentUi("bedroll", "Bedroll"),
    EquipmentUi("bell", "Bell"),
    EquipmentUi("blanket", "Blanket"),
    EquipmentUi("block-and-tackle", "Block and Tackle"),
    EquipmentUi("book", "Book"),
    EquipmentUi("caltrops", "Caltrops", EquipmentKind.CONSUMABLE),
    EquipmentUi("candle", "Candle", EquipmentKind.CONSUMABLE),
    EquipmentUi("case-map", "Map or Scroll Case"),
    EquipmentUi("chain", "Chain (10 ft)"),
    EquipmentUi("climbers-kit", "Climber's Kit"),
    EquipmentUi("component-pouch", "Component Pouch"),
    EquipmentUi("crowbar", "Crowbar"),
    EquipmentUi("explorers-pack", "Explorer's Pack"),
    EquipmentUi("grappling-hook", "Grappling Hook"),
    EquipmentUi("healers-kit", "Healer's Kit", EquipmentKind.CONSUMABLE, quantity = 10),
    EquipmentUi("holy-symbol", "Holy Symbol"),
    EquipmentUi("hourglass", "Hourglass"),
    EquipmentUi("hunting-trap", "Hunting Trap"),
    EquipmentUi("ink", "Ink"),
    EquipmentUi("ladder", "Ladder (10 ft)"),
    EquipmentUi("lamp", "Lamp"),
    EquipmentUi("lantern-bullseye", "Bullseye Lantern"),
    EquipmentUi("lantern-hooded", "Hooded Lantern"),
    EquipmentUi("lock", "Lock"),
    EquipmentUi("magnifying-glass", "Magnifying Glass"),
    EquipmentUi("manacles", "Manacles"),
    EquipmentUi("mess-kit", "Mess Kit"),
    EquipmentUi("oil", "Oil Flask", EquipmentKind.CONSUMABLE),
    EquipmentUi("paper", "Paper", EquipmentKind.CONSUMABLE),
    EquipmentUi("parchment", "Parchment", EquipmentKind.CONSUMABLE),
    EquipmentUi("piton", "Piton", EquipmentKind.CONSUMABLE),
    EquipmentUi("pole", "Pole (10 ft)"),
    EquipmentUi("potion-healing", "Potion of Healing", EquipmentKind.CONSUMABLE),
    EquipmentUi("rations", "Rations (1 day)", EquipmentKind.RATIONS),
    EquipmentUi("rope-hempen", "Hempen Rope (50 ft)"),
    EquipmentUi("rope-silk", "Silk Rope (50 ft)"),
    EquipmentUi("shovel", "Shovel"),
    EquipmentUi("signal-whistle", "Signal Whistle"),
    EquipmentUi("spellbook", "Spellbook"),
    EquipmentUi("spikes-iron", "Iron Spikes", EquipmentKind.CONSUMABLE, quantity = 10),
    EquipmentUi("spyglass", "Spyglass"),
    EquipmentUi("tent", "Tent"),
    EquipmentUi("tinderbox", "Tinderbox"),
    EquipmentUi("torch", "Torch", EquipmentKind.CONSUMABLE),
    EquipmentUi("waterskin", "Waterskin"),
    EquipmentUi("thieves-tools", "Thieves' Tools", EquipmentKind.TOOL),
    EquipmentUi("disguise-kit", "Disguise Kit", EquipmentKind.TOOL),
    EquipmentUi("herbalism-kit", "Herbalism Kit", EquipmentKind.TOOL),
    EquipmentUi("shield", "Shield", EquipmentKind.ARMOR, details = "+2 AC while worn", shieldBonus = 2),
    EquipmentUi("leather-armor", "Leather Armor", EquipmentKind.ARMOR, details = "AC 11 + DEX"),
    EquipmentUi("studded-leather", "Studded Leather Armor", EquipmentKind.ARMOR, details = "AC 12 + DEX"),
    EquipmentUi("chain-shirt", "Chain Shirt", EquipmentKind.ARMOR, details = "AC 13 + DEX (max 2)"),
    EquipmentUi("scale-mail", "Scale Mail", EquipmentKind.ARMOR, details = "AC 14 + DEX (max 2)"),
    EquipmentUi("breastplate", "Breastplate", EquipmentKind.ARMOR, details = "AC 14 + DEX (max 2)"),
    EquipmentUi("half-plate", "Half Plate Armor", EquipmentKind.ARMOR, details = "AC 15 + DEX (max 2)"),
    EquipmentUi("ring-mail", "Ring Mail", EquipmentKind.ARMOR, details = "AC 14"),
    EquipmentUi("chain-mail", "Chain Mail", EquipmentKind.ARMOR, details = "AC 16"),
    EquipmentUi("splint-armor", "Splint Armor", EquipmentKind.ARMOR, details = "AC 17"),
    EquipmentUi("plate-armor", "Plate Armor", EquipmentKind.ARMOR, details = "AC 18"),
)
